project 'RAC_OC.xcodeproj'
use_frameworks!
target 'RAC_OC' do
pod 'ReactiveCocoa', '~> 4.0.2-alpha-1'
end

target 'RAC_Command' do
pod 'ReactiveCocoa', '~> 4.0.2-alpha-1'
end

target 'RAC_过滤' do
pod 'ReactiveCocoa', '~> 4.0.2-alpha-1'
end

target 'RAC_映射' do
    pod 'ReactiveCocoa', '~> 4.0.2-alpha-1'
end

target 'RAC_组合' do
    pod 'ReactiveCocoa', '~> 4.0.2-alpha-1'
end


target 'RAC_MVVM' do
    pod 'ReactiveCocoa', '~> 4.0.2-alpha-1'
    pod 'AFNetworking', '~> 3.1.0'
end
